export const skillsData = [
  {
    name: 'HTML',
    level: 30,
    color: '#e34f26',
    icon: 'html5',
  },
  {
    name: 'CSS',
    level: 50,
    color: '#2980b9',
    icon: 'css3',
  },
  {
    name: 'JavaScript',
    level: 80,
    color: '#f1e05a',
    icon: 'js',
  },
  {
    name: 'React',
    level: 90,
    color: '#61dafb',
    icon: 'react',
  },
  {
    name: 'NodeJS',
    level: 100,
    color: '#6c5ce7',
    icon: 'nodejs',
  },
  {
    name: 'Express',
    level: 10,
    color: '#6c5ce7',
    icon: 'express',
  },
  {
    name: 'MongoDB',
    level: 70,
    color: '#6c5ce7',
    icon: 'mongodb',
  },
  {
    name: 'MySQL',
    level: 80,
    color: '#6c5ce7',
    icon: 'mysql',
  },
  {
    name: 'Git',
    level: 30,
    color: '#6c5ce7',
    icon: 'git',
  },
  {
    name: 'Gulp',
    level: 40,
    color: '#6c5ce7',
    icon: 'gulp',
  },
  {
    name: 'Webpack',
    level: 50,
    color: '#6c5ce7',
    icon: 'webpack',
  },
  {
    name: 'Babel',
    level: 60,
    color: '#6c5ce7',
    icon: 'babel',
  },
  {
    name: 'Styled Components',
    level: 10,
    color: '#6c5ce7',
    icon: 'styled-components',
  },
  {
    name: 'SASS',
    level: 14,
    color: '#6c5ce7',
    icon: 'sass',
  },
  {
    name: 'LESS',
    level: 56,
    color: '#6c5ce7',
    icon: 'less',
  },
]